#!/bin/sh
#
# Bootstrap script for setting up a new OSX machine
#
# This should be idempotent so it can be run multiple times.
#

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
~/.local/bin/yadm submodule update --recursive --init

system_type=$(uname -s)
distro=$(grep ^ID /etc/os-release 2>/dev/null| cut -d= -f2-)

# macOS
if [ "$system_type" = "Darwin" ]; then
    echo "Deploying on macOS/Darwin"

    # requires xcode and tools!
    if ! command -v xcode-select -p &> /dev/null
    then
        echo "XCode must be installed! (run xcode-select --install)"
        xcode-select --install
    else
        echo "Xcode already installed"
    fi

    # homebrew
    if ! command -v /opt/homebrew/bin/brew &> /dev/null
    then
        echo 'brew must be installed! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)")'
    else
        echo "Homebrew already installed. Getting updates..."
        /opt/homebrew/bin/brew update
        /opt/homebrew/bin/brew doctor
    fi

    echo ">>> Installing brew packages.."
    if [ -f ~/.config/macOS/Brewfile ]; then
        /opt/homebrew/bin/brew bundle install --file ~/.config/macOS/Brewfile
    else
        echo "No Brewfile found!"
    fi # end Brewfile

    # iTerm2
    iterm2_installed=$(brew list | grep iterm2)
    if [ -n $iterm2_installed ] >/dev/null 2>&1; then
     echo "iTerm2 Installed"
        if [ -d "$HOME/.iterm2" ]; then
            echo "Setting iTerm preference folder"
            defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
         fi
    fi # End iTerm2
    
fi # end macOS

# WSL Linux
if [ "$system_type" = "Linux" ]; then
    echo "Deploying on WSL Linux"
    if [ "$distro" = "fedora" ]; then
        echo "Fedora detected"
        if ! command -v dnf &> /dev/null
        then
            echo 'dnf must be installed!'
        else
            echo "dnf already installed. Getting updates..."
            sudo dnf check-update
            # Install yadm
            sudo dnf config-manager addrepo --from-repofile=https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_42/home:TheLocehiliosan:yadm.repo
            sudo dnf install -y  yadm
        fi
    elif [ "$distro" = "Ubuntu" ]; then
        echo "Ubuntu detected"
        if ! command -v apt &> /dev/null
        then
            echo 'apt must be installed!'
        else
            echo "apt already installed. Getting updates..."
            sudo apt update && sudo apt upgrade -y
        fi
    else
        echo "Distro not detected"
    fi # end distro check
fi # end WSL


# Install Fish Plugins
# Add if macOS or Linux switch
# fish_shell=$(which fish)
# if ! command -v $fish_shell &> /dev/null
# then
#     echo 'Fish Shell not installed!'
# else
#     echo "Fish Shell installed...Installing packages"
#     $fish_shell -c "fisher install miralize/homebrew-aliases-fish"
# fi # End fish shell

# done
echo "Bootstrapping complete"
